config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'signup', to: 'users#new'

  resources :users
  resources :micro_posts

end

app/models/micro_post.rb
class MicroPost < ActiveRecord::Base
  belongs_to :user
  validates :text, length: {maximum: 140}, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts
  validates :name, :email, presence: true, length: { maximum: 100 }
  validates :email, format: { with: /\A[\w*+\-.~&]+@[a-z\-\d]+(?:\.[a-z\-\d]+)*\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  before_save { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 },
                       format: { with: /(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s)(?=.*\W).+/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/micro_posts_controller.rb
class MicroPostsController < ApplicationController
  before_action :set_micro_post, only: [:show, :edit, :update, :destroy]

  # GET /micro_posts
  # GET /micro_posts.json
  def index
    @micro_posts = MicroPost.includes(:user).all
  end

  # GET /micro_posts/1
  # GET /micro_posts/1.json
  def show
  end

  # GET /micro_posts/new
  def new
    @micro_post = MicroPost.new
  end

  # GET /micro_posts/1/edit
  def edit
  end

  # POST /micro_posts
  # POST /micro_posts.json
  def create
    @micro_post = MicroPost.new(micro_post_params)

    respond_to do |format|
      if @micro_post.save
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully created.' }
        format.json { render :show, status: :created, location: @micro_post }
      else
        format.html { render :new }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /micro_posts/1
  # PATCH/PUT /micro_posts/1.json
  def update
    respond_to do |format|
      if @micro_post.update(micro_post_params)
        format.html { redirect_to @micro_post, notice: 'Micro post was successfully updated.' }
        format.json { render :show, status: :ok, location: @micro_post }
      else
        format.html { render :edit }
        format.json { render json: @micro_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /micro_posts/1
  # DELETE /micro_posts/1.json
  def destroy
    @micro_post.destroy
    respond_to do |format|
      format.html { redirect_to micro_posts_url, notice: 'Micro post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micro_post
      @micro_post = MicroPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micro_post_params
      params.require(:micro_post).permit(:user_id, :text)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end

  def help
  end

  def about
  end

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by_id(params[:id])
    render 'index' if @user.nil?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
      flash[:success] = "Welcome #{@user.name}!"
    else
      flash[:warning] = 'Please retry!'
      render 'new'
    end
  end

  def edit

  end

  def update

  end

  def delete

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/micro_posts_helper.rb
module MicroPostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
  # Returns the gravatar image corresponding to the passed in user
  #
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag gravatar_url, alt: "#{user.name} gravatar", class: 'gravatar'
  end
end

app/views/layouts/application.html.haml
!!!
%html{lang: 'en'}

  %head
    %title
      = yield :title_comp
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1', charset: 'UTF-8'}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'shared/shim'

  %body
    = render 'shared/header'

    .container
      = render 'shared/flash'

      = yield

      = render 'shared/footer'

      = debug(params) if Rails.env.development?

app/views/micro_posts/_form.html.haml
= form_for(@micro_post) do |f|
  - if @micro_post.errors.any?
    #error_explanation
      %h2
        = pluralize(@micro_post.errors.count, "error")
        prohibited this micro_post from being saved:
      %ul
        - @micro_post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :user_id
    %br/
    = f.number_field :user_id
  .field
    = f.label :text
    %br/
    = f.text_area :text
  .actions
    = f.submit

app/views/micro_posts/edit.html.haml
%h1 Editing Micro Post
= render 'form'
= link_to 'Show', @micro_post
|
= link_to 'Back', micro_posts_path

app/views/micro_posts/index.html.haml
%p#notice= notice
%h1 Listing Micro Posts

%table
  %thead
    %tr
      %th User
      %th Text
      %th{:colspan => "3"}
  %tbody
    - @micro_posts.each do |micro_post|
      %tr
        %td= micro_post.user_id
        %td= micro_post.text
        %td= link_to 'Show', micro_post
        %td= link_to 'Edit', edit_micro_post_path(micro_post)
        %td= link_to 'Destroy', micro_post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Micro post', new_micro_post_path
%br/
- @micro_posts.each do |p|
  %p= p.text
  %p= p.user.name

app/views/micro_posts/new.html.haml
%h1 New Micro Post
= render 'form'
= link_to 'Back', micro_posts_path

app/views/micro_posts/show.html.haml
%p#notice= notice
%p
  %strong User:
  = @micro_post.user_id
%p
  %strong Text:
  = @micro_post.text
= link_to 'Edit', edit_micro_post_path(@micro_post)
|
= link_to 'Back', micro_posts_path

app/views/shared/_flash.html.haml
- flash.each do |msg_type, msg|
  .alert{class: "alert-#{msg_type}"}
    = msg

app/views/shared/_footer.html.haml
%footer.footer
  %small
    The
    = link_to 'SWEET THING', 'http://msn.com'
  %nav
    %ul
      %li
        = link_to 'About', about_path
      %li
        = link_to 'Contact', contact_path
      %li
        = link_to 'News', 'http://rubyonrails.org', target: '_blank'

app/views/shared/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to 'sample app', home_path, id: 'logo'
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to 'Home', home_path
        %li
          = link_to 'Help', help_path
        %li
          = link_to 'Log in', 'login_path'

app/views/shared/_shim.html.haml
/[if lt IE 9] <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>

app/views/shared/_user_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains
      = pluralize(@user.errors.size, 'error')
    %ul
      - @user.errors.full_messages.each do |msg|
        %li
          = msg

app/views/static_pages/about.html.haml
- provide :title_comp, 'About'
%h1
  About
%h2
  This is my stuff

app/views/static_pages/contact.html.haml
- provide :title_comp, 'Contact'
%h1
  Contact
%p
  Reach me at:
  = link_to "mike's", 'http://msn.com'

app/views/static_pages/help.html.haml
%h1 StaticPages#help
%p Find me in app/views/static_pages/help.html.erb
- provide :title_comp, 'Help'

app/views/static_pages/home.html.haml
- provide :title_comp, 'Home'
.center.jumbotron
  %h1
    Welcome to the App
  %h2
    This is the home page for the
    = link_to 'SWEET THING', 'http://msn.com'
    app

  = link_to 'Sign up now', signup_path, class: 'btn btn-lg btn-primary'

= link_to image_tag('rails.png', alt: 'Rails logo'), 'http://rubyonrails.org', target: '_blank'

app/views/users/new.html.haml
- provide :title_comp, 'Signup'

%h1
  Sign up

.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |form|
      = render 'shared/user_error_messages'

      = form.label :name
      = form.text_field :name, class: 'form-control'

      = form.label :email
      = form.email_field :email, class: 'form-control'

      = form.label :password
      = form.password_field :password, class: 'form-control'

      = form.label :password_confirmation, 'Password Confirmation'
      = form.password_field :password_confirmation, class: 'form-control'

      = form.submit 'Create User', class: 'btn btn-primary'

app/views/users/show.html.haml
- provide :title, @user.name

.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.name